export default {
  SET_PASS_DATA: 'SET_PASS_DATA',
  SET_PASS_STORY_IMAGE: 'SET_PASS_STORY_IMAGE',
  SET_PASS_STORY_VIDEO: 'SET_PASS_STORY_VIDEO',
  SET_REFRESH_HOME: 'SET_REFRESH_HOME',
  SET_REFRESH_HOME_VIDEO: 'SET_REFRESH_HOME_VIDEO',
  SWITCH_TO_TAB_INDEX: 'SWITCH_TO_TAB_INDEX',
};
